### PR TITLE
Implement Clone for Client & Connection

### PR DESCRIPTION
**Pull request by mikhaillav**
Sorry, im new in rust, maybe this is not greatest way to do this. But still

### CODE REVIEW

**Comment by mikhaillav** [comment]
I don't think [this](https://github.com/NetrexMC/RakNet/pull/61/files#diff-1b84118fef4e05f6f4c73c9ad3c5d469ec065f0ef62e20448683dadf6f281c6dR46) and [this](https://github.com/NetrexMC/RakNet/pull/61/files#diff-1b84118fef4e05f6f4c73c9ad3c5d469ec065f0ef62e20448683dadf6f281c6dR99) changes required (probably I forked outdated version)

**Comment by AndreasHGK** [comment]
Why would you want to imlement Clone on these?

**Comment by mikhaillav** [comment]
Using in different threads for example

**Comment by Adrian8115** [comment]
This is really useful for espacilly me, I am having a recv loop in one thread and a sender in a hashmap for the clients...
Thx!

**Pull request closed without merging**
